# Generated by Django 3.2.16 on 2025-04-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredients_anount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='anount',
            new_name='amount',
        ),
    ]
