# Generated by Django 3.2.16 on 2025-04-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
